apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil42
  name: wil42
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil42-playground
status:
  loadBalancer: {}